/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import newcompiler.Utils.TextLineNumber;
import org.fife.ui.rsyntaxtextarea.RSyntaxTextArea;
import org.fife.ui.rsyntaxtextarea.SyntaxConstants;
import org.fife.ui.rtextarea.RTextScrollPane;

/**
 *
 * @author Hugo Luna
 */
public class VistaInicio extends javax.swing.JFrame {

    public RSyntaxTextArea editor;
    public RTextScrollPane sp;
    
    /**
     * Creates new form vistaInicio
     */
    public VistaInicio() {
        initComponents();
        this.setResizable(false);
        editor = new RSyntaxTextArea(20, 60);
        editor.setSyntaxEditingStyle(SyntaxConstants.SYNTAX_STYLE_JAVA);
        
        editor.setCodeFoldingEnabled(true);
        editor.setMarkOccurrences(true);
        
        sp = new RTextScrollPane(editor);
        sp.setSize(740, 679);
        contenedorPrincipal.add(sp);
        /*
        TextLineNumber tln = new TextLineNumber(editor);
        scroll.setRowHeaderView(tln);
        */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedorPrincipal = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        accionNuevo = new javax.swing.JMenuItem();
        accionAbrir = new javax.swing.JMenuItem();
        accionGuardar = new javax.swing.JMenuItem();
        accionGuardarComo = new javax.swing.JMenuItem();
        accionSalir = new javax.swing.JMenuItem();
        accionDeshacer = new javax.swing.JMenu();
        deshacer = new javax.swing.JMenuItem();
        rehacer = new javax.swing.JMenuItem();
        cortar = new javax.swing.JMenuItem();
        copiar = new javax.swing.JMenuItem();
        pegar = new javax.swing.JMenuItem();
        accionCompilarMenu = new javax.swing.JMenu();
        accionCompilar = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        documentacion = new javax.swing.JMenuItem();
        acerca = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout contenedorPrincipalLayout = new javax.swing.GroupLayout(contenedorPrincipal);
        contenedorPrincipal.setLayout(contenedorPrincipalLayout);
        contenedorPrincipalLayout.setHorizontalGroup(
            contenedorPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 740, Short.MAX_VALUE)
        );
        contenedorPrincipalLayout.setVerticalGroup(
            contenedorPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 679, Short.MAX_VALUE)
        );

        jMenu1.setText("Archivo");

        accionNuevo.setText("Nuevo");
        jMenu1.add(accionNuevo);

        accionAbrir.setText("Abrir");
        accionAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accionAbrirActionPerformed(evt);
            }
        });
        jMenu1.add(accionAbrir);

        accionGuardar.setText("Guardar");
        jMenu1.add(accionGuardar);

        accionGuardarComo.setText("Guardar como");
        jMenu1.add(accionGuardarComo);

        accionSalir.setText("Salir");
        jMenu1.add(accionSalir);

        jMenuBar1.add(jMenu1);

        accionDeshacer.setText("Editar");

        deshacer.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_MASK));
        deshacer.setText("Deshacer");
        accionDeshacer.add(deshacer);

        rehacer.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        rehacer.setText("Rehacer");
        rehacer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rehacerActionPerformed(evt);
            }
        });
        accionDeshacer.add(rehacer);

        cortar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        cortar.setText("Cortar");
        accionDeshacer.add(cortar);

        copiar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        copiar.setText("Copiar");
        accionDeshacer.add(copiar);

        pegar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        pegar.setText("Pegar");
        accionDeshacer.add(pegar);

        jMenuBar1.add(accionDeshacer);

        accionCompilarMenu.setText("Ejecutar");

        accionCompilar.setText("Compilar");
        accionCompilarMenu.add(accionCompilar);

        jMenuBar1.add(accionCompilarMenu);

        jMenu3.setText("Ayuda");

        documentacion.setText("Documentacion");
        jMenu3.add(documentacion);

        acerca.setText("Acerca");
        jMenu3.add(acerca);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedorPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedorPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rehacerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rehacerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rehacerActionPerformed

    private void accionAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accionAbrirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accionAbrirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenuItem accionAbrir;
    public javax.swing.JMenuItem accionCompilar;
    private javax.swing.JMenu accionCompilarMenu;
    private javax.swing.JMenu accionDeshacer;
    public javax.swing.JMenuItem accionGuardar;
    public javax.swing.JMenuItem accionGuardarComo;
    public javax.swing.JMenuItem accionNuevo;
    public javax.swing.JMenuItem accionSalir;
    public javax.swing.JMenuItem acerca;
    private javax.swing.JPanel contenedorPrincipal;
    public javax.swing.JMenuItem copiar;
    public javax.swing.JMenuItem cortar;
    public javax.swing.JMenuItem deshacer;
    public javax.swing.JMenuItem documentacion;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JMenuItem pegar;
    public javax.swing.JMenuItem rehacer;
    // End of variables declaration//GEN-END:variables
}
